### ISSUE TITLE
Using DECO for paired samples

### ISSUE THREAD

**Issue by gilhornung** [fjcamlab/deco#1]
Hi,
I have an experimental design as follows:
Paired samples, patients before and after treatment. The treatment is either real or mock. I want to fond the differences between the real treatment and the mock.
I there a way to do it using DECO? Because DECO compares only two conditions. Maybe I can work around it by calculating the log-fold change before and after treatment for each patient and then use that as an input?

Thank you,

Gil

**Comment by fjcamlab** [comment]
Hi @gilhornung, 

Yes, a log fold-change matrix would fit as input. You may also consider calculating a difference matrix (`input = after - before`, for each patient) if your original data is already log-scale. Then, you can compare real or mock treatment in both ways.

For future comparisons, note that DECO also allows you to apply a multiclass experimental design.

Best,
Francisco

**Comment by gilhornung** [comment]
Thank you, Francisco.

And how would you go about comparing the "real" and "mock"?

In the limma framework, the treatment can be divided into 4 levels: real_before, real_after, mock_before, mock_after. And I am interested in the contrast:
(real_after - real_before) - (mock_after - mock_before)

How can the "multiclass" design of DECO be used to perform this type of analysis?

**Comment by fjcamlab** [comment]
Here, multiclass design is optimized to restrict the election of samples during the subsampling procedure, and then, every class will be contrasted in 2vs2 comparisons. At this moment, DECO can not compare the contrast you are interested in since it is a two-step design.

Anyway, the log fold-change matrix you proposed before would be a good approach to address your contrast hypothesis.

**Comment by gilhornung** [comment]
Thank you!
